[project]
name = "plateerag-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.14",
    "psutil>=7.0.0",
    "pynvml>=12.0.0",
    "uvicorn>=0.35.0",
]
